import main from '../../assets/images/main-big-flower.png';
import m5 from '../../assets/images/m5.png';
import m6 from '../../assets/images/m6.png';
import m7 from '../../assets/images/m7.png';
import m8 from '../../assets/images/m8.png';
import m9 from '../../assets/images/m9.png';
import m10 from '../../assets/images/m10.png';

export const plants = [
  {
    id: 1,
    name: 'Barberton Daisy',
    price: 119.0,
    saleprice: 99.0,
    img: m5,
    quantity: '33',
    category: 'seeds',
    status: 'all',
  },
  {
    id: 2,
    name: 'Angel Wing Begonia',
    price: 119.0,
    saleprice: 99.0,
    img: main,
    quantity: '33',
    category: 'gardening',
    status: 'new',
  },
  {
    id: 3,
    name: 'African Violet',
    price: 119.0,
    saleprice: 99.0,
    img: m7,
    quantity: '33',
    category: 'seeds',
    status: 'new',
  },
  {
    id: 4,
    name: 'Beach Spider Lily',
    price: 119.0,
    saleprice: 99.0,
    img: m8,
    quantity: '33',
    category: 'gardening',
    status: 'new',
  },
  {
    id: 5,
    name: 'Blushing Bromeliad',
    price: 119.0,
    saleprice: 99.0,
    img: m9,
    quantity: '33',
    category: 'seeds',
    status: 'all',
  },
  {
    id: 6,
    name: 'Aluminium Plant',
    price: 119.0,
    saleprice: 99.0,
    img: main,
    quantity: '33',
    category: 'gardening',
    status: 'sale',
  },
  {
    id: 7,
    name: "Bird's Nest Fern",
    price: 119.0,
    saleprice: 99.0,
    img: m10,
    quantity: '33',
    category: 'plants',
    status: 'sale',
  },
  {
    id: 8,
    name: 'Broadleaf Lady Palm',
    price: 119.0,
    saleprice: 99.0,
    img: main,
    quantity: '33',
    category: 'seeds',
    status: 'all',
  },
  {
    id: 9,
    name: 'Chinese Evergreen',
    price: 119.0,
    saleprice: 99.0,
    img: m5,
    quantity: '33',
    category: 'seeds',
    status: 'all',
  },
  {
    id: 10,
    name: 'Blushing Bromeliad',
    price: 119.0,
    saleprice: 99.0,
    img: m6,
    quantity: '33',
    category: 'plants',
    status: 'all',
  },
  {
    id: 11,
    name: 'African Violet',
    price: 119.0,
    saleprice: 99.0,
    img: main,
    quantity: '33',
    category: 'seeds',
    status: 'sale',
  },
  {
    id: 12,
    name: 'Barberton Daisy',
    price: 119.0,
    saleprice: 99.0,
    img: m7,
    quantity: '33',
    category: 'plants',
    status: 'sale',
  },
];